Repository uc-cdis/cloud-automation, pull requests merged in 2020-12, with the labels that each got.

#1471 chore(qa): Upgrade Jenkins2
  Docker/Jenkins2/Dockerfile
Labels: test-portal-homepageTest

#1474 task(qa): Create gen3 cli command to run gen3-qa tests (automated access checks)
  gen3/bin/gen3qa-run.sh
  kube/services/jobs/gen3qa-check-bucket-access-job.yaml
Labels: test-portal-homepageTest

#1475 fix(qa): Enable communication between Selenium and dataguids.org
  files/squid_whitelist/web_whitelist
Labels: test-portal-homepageTest

#1477 chore(ci): Introduce new labels to skip unnecessary pipeline stages
  Jenkinsfile
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1476 chore(qa): Improve gen3qa-check-bucket-access k8s job
  gen3/bin/gen3qa-run.sh
  kube/services/jobs/gen3qa-check-bucket-access-job.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1459 chore(qa): Install Ruby on Jenkins Worker
  Docker/Jenkins-Worker/Dockerfile
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1478 fix(qa): Better ReadinessProbe for gen3qa-check-bucket-access job
  kube/services/jobs/gen3qa-check-bucket-access-job.yaml
Labels: test-portal-homepageTest

#1463 chore(qa): Bumping up Selenium session request timeout
  kube/services/selenium/selenium-hub-deployment.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1464 fix(ci): Adopt new selenium4 var SE_NODE_MAX_CONCURRENT_SESSIONS to configure more sessions per node
  kube/services/selenium/selenium-node-chrome-deployment.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1472 chore(gstatic): add gstatic.com to the whitelist
  files/squid_whitelist/web_whitelist
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-apis-dbgapTest, test-google-googleServiceAccountTest

#1479 fix(qa): Skip network policy deletion for doc-only PRs
  Jenkinsfile
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1481 Revert "chore(gstatic): add gstatic.com to the whitelist"
  files/squid_whitelist/web_whitelist
Labels: skip-awshelper-build-wait

#1480 chore(ci): Keeping a copy of our CI dashboards
  files/grafana/dashboards/ci-metrics.json
  files/grafana/dashboards/general-ci-metrics.json
  files/grafana/dashboards/jenkins-monitoring.json
  files/grafana/dashboards/k6-load-testing-results.json
  files/grafana/dashboards/selenium-observability.json
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1482 fix(gen3qa-run): Improve polling logic to wait for Selenium to be ready
  gen3/bin/gen3qa-run.sh
Labels: test-portal-homepageTest

#1376 chore(observability): Enable metrics scraping for revproxy
  gen3/bin/kube-setup-revproxy.sh
  kube/services/revproxy/logrotate-nginx.conf
  kube/services/revproxy/nginx.conf
  kube/services/revproxy/revproxy-deploy.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-google-googleServiceAccountTest

#1483 Fix/better bootstrapping for nginx prom exporter in presigned url
  gen3/lib/testData/test1.manifest.g3k/expectedFenceResult.yaml
  kube/services/fence/fence-deploy.yaml
  kube/services/presigned-url-fence/presigned-url-fence-deploy.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1484 chore(logs): Send nginx access log entries to stdout
  Docker/python-nginx/python3.6-alpine3.7/nginx.conf
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1466 docs(cognito): Clarify metadata exchange instructions
  tf_files/aws/cognito/README.md
Labels: doc-only

#1485 chore(pybase): Adopt parent img from quay to avoid pull rate limit errors
  Docker/python-nginx/python3.6-alpine3.7/Dockerfile
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest
