Repository uc-cdis/cloud-automation, pull requests merged in 2020-09, with the labels that each got.

#1396 COVID19 ETL memory 512Mi -> 1024Mi
  kube/services/jobs/covid19-etl-job.yaml
Labels: test-google-googleServiceAccountRemovalTest

#1388 chore(qa): add label magic support
  Jenkinsfile
Labels: test-portal-homepageTest

#1404 chore(squid_proxy): add docs.google.com
  files/squid_whitelist/web_whitelist
Labels: test-google-googleServiceAccountTest

#1408 chore(ci): Wait a bit longer for data-portal pods to come up
  gen3/bin/kube-wait4-pods.sh
Labels: test-portal-homepageTest
