Repository uc-cdis/cloud-automation, pull requests merged in 2020-10, with the labels that each got.

#1418 fix(path): fix the path to the template ...
  gen3/bin/gcp-bucket-manifest.sh
Labels: test-portal-homepageTest

#1419 chore(utilityvm): add user_policy variable
  .secrets.baseline
  gen3/lib/aws.sh
  tf_files/aws/modules/utility-vm/README.md
  tf_files/aws/modules/utility-vm/cloud.tf
  tf_files/aws/modules/utility-vm/variables.tf
  tf_files/aws/utility_vm/root.tf
  tf_files/aws/utility_vm/variables.tf
Labels: test-apis-cleverSafeTest

#1422 fix(qa): Max values per tag limit exceeded in InfluxDB
  kube/services/influxdb/influxdb-deployment.yaml
Labels: test-portal-homepageTest

#1421 chore(ci): Wait a bit longer (again) for data-portal pods to come up
  gen3/bin/kube-wait4-pods.sh
Labels: test-portal-homepageTest

#1424 fix(qa): Define submission order for gentestdata
  kube/services/jobs/gentestdata-job.yaml
Labels: test-portal-homepageTest

#1425 Update maintenance.md
  doc/maintenance.md
Labels: doc-only

#1431 feat(access-roll): Added access-backend to kube-roll-all
  gen3/bin/kube-roll-all.sh
Labels: test-portal-homepageTest

#1434 Fix/configmaps del
  gen3/bin/gitops.sh
Labels: test-api-dataUploadTest, test-portal-homepageTest

#1417 fix(jenkinx-pv-size): Updated the size of Jenkins persistent volume.
  kube/services/jenkins/00pvc.yaml
Labels: test-portal-homepageTest

#1438 Pybase: don't wait for wsgi.sock
  Docker/python-nginx/python2.7-alpine3.7/dockerrun.sh
  Docker/python-nginx/python3.6-alpine3.7/dockerrun.sh
Labels: test-apis-etlTest
