Repository uc-cdis/cloud-automation, pull requests merged in 2021-11, with the labels that each got.

#1773 feat(python): new python 3.10 base image based off 3.6-buster
  Docker/python-nginx/README.md
  Docker/python-nginx/python3.10-buster/Dockerfile
  Docker/python-nginx/python3.10-buster/app/main.py
  Docker/python-nginx/python3.10-buster/app/uwsgi.ini
  Docker/python-nginx/python3.10-buster/dockerrun.sh
  Docker/python-nginx/python3.10-buster/entrypoint.sh
  Docker/python-nginx/python3.10-buster/logrotate-nginx.conf
  Docker/python-nginx/python3.10-buster/nginx.conf
  Docker/python-nginx/python3.10-buster/supervisord.ini
  Docker/python-nginx/python3.10-buster/uwsgi.conf
  Docker/python-nginx/python3.10-buster/uwsgi.ini
  Jenkinsfile
Labels: test-guppy-guppyTest

#1782 docs(arborist): important clarification/warning about expose more of Arborist's API
  kube/services/revproxy/gen3.nginx.conf/arborist-service.conf
Labels: doc-only

#1788 Increase data-portal livenessProbe failureThreshold to 10
  kube/services/portal/portal-deploy.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-pidgin-getCoremetadataTest

#1795 whitelist charts.bitnami.com
  files/squid_whitelist/web_whitelist
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-indexingPageTest, test-apis-metadataIngestionTest

#1793 (PXP-5168): Add param to dcf-dataservice validate job
  kube/services/jobs/replicate-validation-job.yaml
Labels: skip-gen3-helper-tests

#1790 Address external PR's
  tf_files/aws/modules/eks/cloud.tf
  tf_files/aws/modules/eks/variables.tf
  tf_files/aws/modules/squid/cloud.tf
  tf_files/aws/modules/squid/variables.tf
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-indexingPageTest, test-apis-metadataIngestionTest

#1797 (PXP-5168): Add FORCE_CREATE_MANIFEST param to env
  kube/services/jobs/replicate-validation-job.yaml
Labels: test-apis-auditServiceTest

#1705 [PXP-7690] Atlas deployment scripts
  gen3/bin/kube-setup-ohdsi-tools.sh
  kube/services/cohort-middleware/cohort-middleware-deploy.yaml
  kube/services/cohort-middleware/cohort-middleware-service.yaml
  kube/services/netpolicy/gen3/services/revproxy_netpolicy.yaml
  kube/services/ohdsi-atlas/README.md
  kube/services/ohdsi-atlas/ohdsi-atlas-deploy.yaml
  kube/services/ohdsi-atlas/ohdsi-atlas-service-elb.yaml
  kube/services/ohdsi-atlas/ohdsi-atlas-service.yaml
  kube/services/ohdsi-webapi/ohdsi-webapi-deploy.yaml
  kube/services/ohdsi-webapi/ohdsi-webapi-service-elb.yaml
  kube/services/ohdsi-webapi/ohdsi-webapi-service.yaml
  kube/services/revproxy/gen3.nginx.conf/cohort-middleware-service.conf
  kube/services/revproxy/gen3.nginx.conf/ohdsi-atlas-service.conf
  kube/services/revproxy/gen3.nginx.conf/ohdsi-webapi-service.conf
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#1785 chore: adding cronjob version check to gitops-sync
  gen3/bin/gitops.sh
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests
