Repository uc-cdis/cloud-automation, pull requests merged in 2021-06, with the labels that each got.

#1620 add midrc to squid whitelist
  files/squid_whitelist/web_wildcard_whitelist
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1623 Fix ENABLE_SVC_METRICS_SCRAPING logic
  Docker/python-nginx/python3.6-alpine3.7/dockerrun.sh
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1621 chore(ci-automation): Introduce new Gen3 CLI cmds to mutate k8s configmaps
  gen3/bin/mutate-etl-mapping-config.sh
  gen3/bin/mutate-guppy-config.sh
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1603 PXP-7805 Audit Service SQS
  doc/awsrole.md
  doc/sqs.md
  gen3/bin/awsrole.sh
  gen3/bin/kube-setup-access-backend.sh
  gen3/bin/kube-setup-audit-service.sh
  gen3/bin/kube-setup-fence.sh
  gen3/bin/s3.sh
  gen3/bin/sqs.sh
  gen3/bin/tfplan.sh
  gen3/lib/testData/default/expectedFenceResult.yaml
  gen3/lib/testData/test1.manifest.g3k/expectedFenceResult.yaml
  gen3/lib/utils.sh
  kube/services/audit-service/audit-service-deploy.yaml
  kube/services/fence/fence-deploy.yaml
  kube/services/presigned-url-fence/presigned-url-fence-deploy.yaml
  tf_files/aws/modules/sqs/README.md
  tf_files/aws/modules/sqs/cloud.tf
  tf_files/aws/modules/sqs/outputs.tf
  tf_files/aws/modules/sqs/variables.tf
  tf_files/aws/sqs/cloud.tf
  tf_files/aws/sqs/manifest.json
  tf_files/aws/sqs/outputs.tf
  tf_files/aws/sqs/variables.tf
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1629 chore(ecr): add describe-image command
  gen3/bin/ecr.sh
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1633 fix(ci): New fetchCIEnvs method signature
  Jenkinsfile
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1632 fix(sa-setup): Added initial sa setup so deployments have access to S…
  gen3/bin/kube-setup-audit-service.sh
  gen3/bin/kube-setup-fence.sh
Labels: test-apis-presignedUrlTest

#1634 bump version
  Docker/Jenkins2/Dockerfile
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1631 update jenkins version.
  .secrets.baseline
  Docker/Jenkins/Dockerfile
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-google-googleServiceAccountTest

#1635 Fix(prod-test): Also scan s3 buckets in access check script
  gen3/bin/gen3qa-run.sh
  kube/services/jobs/gen3qa-check-bucket-access-job.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1626 feat(qualys-agent): Added qualy agent configuration to userdata boots…
  flavors/eks/bootstrap-explicit-proxy-docker.sh
  flavors/eks/bootstrap-with-security-updates.sh
  flavors/eks/bootstrap.sh
  tf_files/aws/eks/root.tf
  tf_files/aws/eks/variables.tf
  tf_files/aws/modules/eks-nodepool/templates.tf
  tf_files/aws/modules/eks-nodepool/variables.tf
  tf_files/aws/modules/eks/cloud.tf
  tf_files/aws/modules/eks/templates.tf
  tf_files/aws/modules/eks/variables.tf
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#1636 fix: throw errors on missing arguments and fix sed -i logic
  gen3/bin/mutate-etl-mapping-config.sh
  gen3/bin/mutate-guppy-config.sh
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1642 chore(observability): Remove Prometheus metrics aggregation
  Docker/python-nginx/python3.6-alpine3.7/dockerrun.sh
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1645 fix(squid): remove redundant/overlapping rules
  files/squid_whitelist/web_whitelist
Labels: test-portal-homepageTest
