Repository uc-cdis/cloud-automation, pull requests merged in 2021-08, with the labels that each got.

#1678 chore(update-ssl-cipher-script): Added initial script for updating ss…
  files/scripts/revproxy-cipher-updater.sh
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1677 feat(sqs-monitoring): Added sqs monitoring
  gen3/bin/sqs.sh
  gen3/lib/g3k_manifest.sh
  tf_files/aws/modules/sqs/cloud.tf
  tf_files/aws/modules/sqs/variables.tf
  tf_files/aws/sqs/cloud.tf
  tf_files/aws/sqs/variables.tf
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-apis-auditServiceTest

#1700 Adding statsd port to the datadog node agent yaml
  kube/services/datadog/datadog-node-agent.yaml
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1702 chore(gentestdata): Allow token expiry date override
  kube/services/jobs/gentestdata-job.yaml
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1704 chore(gen3qa-check-bucket-access): Running gen3-qa tests + embedded selenium-standlone
  kube/services/jobs/gen3qa-check-bucket-access-job.yaml
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1706 fix: do not restrict body size for mds
  kube/services/revproxy/gen3.nginx.conf/metadata-service.conf
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-apis-metadataIngestionTest

#1701 feat(metadata): use manifest to drive config
  gen3/bin/kube-setup-metadata.sh
  kube/services/metadata/metadata-deploy.yaml
Labels: test-google-googleServiceAccountRemovalTest, test-google-googleServiceAccountTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1707 chore(gen3-qa-in-a-box): Prepare jenkins ci worker img for gen3 qa in a box
  Docker/Jenkins-CI-Worker/Dockerfile
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1710 whitelist planx-ci.io
  files/squid_whitelist/web_wildcard_whitelist
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1711 feat(save-logs): save logs of all containers in pod
  gen3/bin/save-failed-pod-logs.sh
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1715 fix(jenkins-disk-cleanup): Run command in the correct container
  files/scripts/jenkins-cronjob.sh
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1714 fix(save-logs): fix variable in loop
  gen3/bin/save-failed-pod-logs.sh
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1717 Chore/hatchery deploy
  kube/services/hatchery/hatchery-deploy.yaml
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1718 fix(jenkins-ci-worker): Fix py3 symlink
  Docker/Jenkins-CI-Worker/Dockerfile
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1716 chore(better-ci): Adopt gen3-qa-in-a-box
  Jenkinsfile
  gen3/lib/g3k.sh
  gen3/test/bootstrapTest.sh
  gen3/test/ec2Test.sh
  gen3/test/fenceStuffTest.sh
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1713 Fix/install libgit2 to unblock py3.8 automation
  Docker/Jenkins-Worker/Dockerfile
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1719 Exclude Fence register blueprint from CSRF check
  kube/services/revproxy/gen3.nginx.conf/fence-service.conf
Labels: test-apis-cleverSafeTest, test-apis-presignedUrlTest
