Repository uc-cdis/cloud-automation, pull requests merged in 2021-03, with the labels that each got.

#1537 Chore/test custom gcp bucket manifest branch
  gen3/bin/gcp-bucket-manifest.sh
Labels: skip-awshelper-build-wait, test-portal-homepageTest

#1538 chore(ci): Adopt poetry for google-bucket-manifest-job
  kube/services/jobs/google-bucket-manifest-job.yaml
Labels: skip-awshelper-build-wait, test-portal-homepageTest

#1540 PXP-7447 Audit service
  gen3/bin/db.sh
  gen3/bin/ecr.sh
  gen3/bin/gitops.sh
  gen3/bin/kube-roll-all.sh
  gen3/bin/kube-setup-audit-service.sh
  gen3/bin/kube-setup-requestor.sh
  gen3/lib/bootstrap/templates/cdis-manifest/manifest.json
  kube/services/audit-service/audit-service-deploy.yaml
  kube/services/audit-service/audit-service-service.yaml
  kube/services/revproxy/gen3.nginx.conf/audit-service.conf
Labels: test-google-googleServiceAccountTest

#1543 ETL job slack notification
  kube/services/jobs/etl-cronjob.yaml
  kube/services/jobs/etl-job.yaml
Labels: test-google-googleServiceAccountTest

#1541 chore(VA):adding qualys to whitelist
  files/squid_whitelist/web_wildcard_whitelist
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#1544 Add slack webhook to nb-etl
  kube/services/jobs/nb-etl-cronjob.yaml
  kube/services/jobs/nb-etl-job.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#1503 chore: updating the selenium hub.
  kube/services/selenium/selenium-hub-deployment.yaml
  kube/services/selenium/selenium-node-chrome-deployment.yaml
Labels: test-portal-homepageTest

#1553 Chore(ci): Dynamic ci envs pool
  Jenkinsfile
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest
