Repository uc-cdis/cloud-automation, pull requests merged in 2021-05, with the labels that each got.

#1592 PXP-8080 fix: disable npm notifier
  kube/services/portal/portal-deploy.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#1593 chore(ci-debugging): Capture logs from restarting pods
  Jenkinsfile
  gen3/bin/kube-wait4-pods.sh
  gen3/bin/reset.sh
  gen3/bin/save-failed-pod-logs.sh
Labels: skip-gen3-helper-tests, test-portal-homepageTest

#1607 Fix teardown method
  Jenkinsfile
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1611 chore(gen3-qa-worker): Add pandas to help with gen3 release date calculations
  Docker/Jenkins-Worker/Dockerfile
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1606 chore(k8sReset-debug): Capture logs and events for Evicted pods
  gen3/bin/save-failed-pod-logs.sh
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1613 chore(reliability): Allow fence-config to override Nginx rate limit.
  Docker/python-nginx/python3.6-alpine3.7/entrypoint.sh
  kube/services/presigned-url-fence/presigned-url-fence-deploy.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1614 update the Dockerfile for jenkins-worker
  Docker/Jenkins-Worker/Dockerfile
Labels: skip-awshelper-build-wait, test-portal-homepageTest
