Repository uc-cdis/cloud-automation, pull requests merged in 2021-04, with the labels that each got.

#1568 python-nginx base image Rust install
  Docker/python-nginx/python3.6-alpine3.7/Dockerfile
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1569 Whitelist download.pytorch.org
  files/squid_whitelist/web_whitelist
Labels: test-sheepdogAndPeregrine-submitFileTest

#1575 choore(test-in-prod): Introduce kill switch for gen3qa-run due to Selenium side car
  gen3/bin/gen3qa-run.sh
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1410 chore(qa): Improve k8s reset debugging
  gen3/bin/save-failed-pod-logs.sh
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1566 chore(squid-whitelist): Add .okta.com to wildcard wl
  files/squid_whitelist/web_wildcard_whitelist
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1557 Add Fence OIDC login metrics to dashboard
  files/dashboard/usage-reports/src/dataHelper.js
  files/dashboard/usage-reports/src/index.html
  files/dashboard/usage-reports/src/reportsMain.js
  files/scripts/reports-cronjob.sh
  gen3/bin/logs.sh
  gen3/lib/logs/daily.sh
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-dataUploadTest

#1535 adding fasi ssh key
  ansible/keys/fasi
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1560 chore(ci-metrics): Network policy for InfluxDB
  kube/services/influxdb/influxdb-policy.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1582 fix(ci): new runIntegrationTests function signature
  Jenkinsfile
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1581 fix(save-failed-pods-logs): Capture logs before namespace is wiped out
  gen3/bin/kube-wait4-pods.sh
  gen3/bin/reset.sh
  gen3/bin/save-failed-pod-logs.sh
Labels: test-portal-homepageTest

#1580 (PXP-7565): Exclude Fence register-user blueprint from CSRF check
  kube/services/revproxy/gen3.nginx.conf/fence-service.conf
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1588 fix(save-logs): Fetch logs from failed pods when K8sReset fails
  gen3/bin/save-failed-pod-logs.sh
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1559 chore(selenium): Document networkpolicies for selenium-hub and nodes.
  kube/services/selenium/selenium-hub-nodes-policy.yaml
  kube/services/selenium/selenium-nodes-hub-policy.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1590 Fix/daily metrics capture non prod envs
  files/scripts/reports-cronjob.sh
  gen3/lib/logs/daily.sh
Labels: test-google-googleServiceAccountTest
