Repository uc-cdis/cloud-automation, pull requests merged in 2021-02, with the labels that each got.

#1511 chore(observability): Enable scraping from the service /metrics endpoint if it exists
  Docker/python-nginx/python3.6-alpine3.7/dockerrun.sh
Labels: skip-awshelper-build-wait, test-portal-homepageTest

#1525 Update access-backend-deploy.yaml
  kube/services/access-backend/access-backend-deploy.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1513 (PXP-6471) Cronjob to update visas hourly
  kube/services/jobs/fence-visa-update-cronjob.yaml
Labels: test-google-googleServiceAccountTest

#1529 Chore/upgrade python within jenkins img
  Docker/Jenkins/Dockerfile
  Docker/Jenkins/install-python3.6.sh
  Docker/Jenkins/install-python3.8.sh
  Jenkinsfile
Labels: skip-awshelper-build-wait, test-portal-homepageTest

#1454 Feat/dynamodb
  doc/dynamodb.md
  gen3/bin/dynamodb.sh
Labels: skip-awshelper-build-wait, test-google-googleServiceAccountTest, test-portal-rasAuthN
