Repository uc-cdis/cloud-automation, pull requests merged in 2021-01, with the labels that each got.

#1490 chore(metrics): Write metrics for every pipeline stage
  Jenkinsfile
Labels: test-portal-homepageTest

#1492 Update gen3 access-token doc
  doc/api.md
Labels: doc-only

#1498 chore(usersync): Fix usersync for Fence PR #810 (Prometheus client integration)
  kube/services/jobs/usersync-job.yaml
Labels: test-portal-homepageTest

#1502 chore(jenkins): Whitelist jenkins.io to support plugins / security maintenance
  files/squid_whitelist/web_wildcard_whitelist
Labels: test-portal-homepageTest

#1500 Chore/misc stuff
  Docker/Jenkins/Dockerfile
  Docker/awshelper/Dockerfile
  files/authorized_keys/ops_team
  files/authorized_keys/squid_authorized_keys_admin
  files/authorized_keys/vpn_authorized_keys_admin
  gen3/lib/aws.sh
  gen3/test/terraformTest.sh
  kube/services/revproxy/gen3.nginx.conf/tty.conf
  tf_files/aws/modules/utility-vm/cloud.tf
  tf_files/aws/modules/utility-vm/variables.tf
  tf_files/aws/utility_admin/README.md
  tf_files/aws/utility_admin/main.tf
  tf_files/aws/utility_admin/manifest.json
  tf_files/aws/utility_admin/variables.tf
  tf_files/aws/utility_vm/manifest.json
  tf_files/aws/utility_vm/variables.tf
Labels: test-google-googleServiceAccountKeyTest

#1494 task(observability): Enable prometheus metrics scraping for indexd
  kube/services/indexd/indexd-deploy.yaml
Labels: test-apis-drsEndpointsTest, test-portal-homepageTest

#1509 fix(qa): Fix the call to the CleanS3 function
  Jenkinsfile
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest

#1504 Add helm repository if it's missing
  gen3/bin/kube-setup-prometheus.sh
Labels: test-google-googleServiceAccountKeyTest

#1515 chore(squid): github-releases.githubusercontent
  files/squid_whitelist/web_whitelist
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-portal-homepageTest
