Repository uc-cdis/cloud-automation, pull requests merged in 2021-09, with the labels that each got.

#1724 fix(header-buffer-size): Increased header buffer size to prevent head…
  Docker/python-nginx/python2.7-alpine3.7/uwsgi.conf
  Docker/python-nginx/python3.6-alpine3.7/uwsgi.conf
  kube/services/revproxy/nginx.conf
Labels: test-apis-centralizedAuth

#1727 fix(zdt): Introduce readinessProbe to indexd
  kube/services/indexd/indexd-deploy.yaml
Labels: test-portal-homepageTest, skip-awshelper-build-wait

#1722 feat(agg-mds-job): add new agg mds job
  kube/services/jobs/README.md
  kube/services/jobs/metadata-aggregate-sync-job.yaml
Labels: skip-gen3-helper-tests, test-apis-metadataIngestionTest

#1721 chore(autoscaling): Trying to fix autoscaler in qaplanetv2
  kube/services/autoscaler/cluster-autoscaler-autodiscover.yaml
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1728 Add Ajo's keys
  files/authorized_keys/ops_team
  files/authorized_keys/squid_authorized_keys_user
  files/authorized_keys/vpn_authorized_keys_admin
Labels: test-portal-homepageTest

#1726 Feat/fence drs
  gen3/bin/kube-setup-revproxy.sh
  gen3/lib/utils.sh
  kube/services/revproxy/gen3.nginx.conf/fence-service-ga4gh.conf
  kube/services/revproxy/gen3.nginx.conf/indexd-service.conf
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-apis-centralizedAuth

#1720 chore(remove-prometheus): Removed kube-setup-promethus from the roll …
  gen3/bin/kube-roll-all.sh
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1729 Feat/squid5
  Docker/squid/Dockerfile
  flavors/squid_auto/startup_configs/squid.conf
Labels: test-apis-centralizedAuth

#1733 chore(thor): Load Thor database credentials into thor pod
  kube/services/thor/thor-deploy.yaml
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1736 fix(gen3qa-check-bucket-access): Pin chromedriver version to fix the gen3qa-check-bucket-access job
  kube/services/jobs/gen3qa-check-bucket-access-job.yaml
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1735 chore(observability): Add datadog py lib to jenkins worker img
  Docker/Jenkins-CI-Worker/Dockerfile
Labels: test-portal-homepageTest, skip-awshelper-build-wait

#1643 chore(observability): Remove Prometheus metrics aggregation - Part 2
  gen3/lib/testData/test1.manifest.g3k/expectedFenceResult.yaml
  gen3/lib/testData/test1.manifest.g3k/expectedSheepdogResult.yaml
  kube/services/fence/fence-deploy.yaml
  kube/services/indexd/indexd-deploy.yaml
  kube/services/presigned-url-fence/presigned-url-fence-deploy.yaml
  kube/services/revproxy/revproxy-deploy.yaml
Labels: test-portal-homepageTest, skip-awshelper-build-wait

#1740 change HOSTNAME to GEN3_ENDPOINT
  kube/services/hatchery/hatchery-deploy.yaml
Labels: skip-gen3-helper-tests, test-apis-auditServiceTest

#1742 chore(qa-bot): Add jira token to secrets
  kube/services/qabot/qabot-deploy.yaml
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests
