Repository uc-cdis/cloud-automation, pull requests merged in 2022-05, with the labels that each got.

#1925 Fix dicom-server orthanc secret
  gen3/bin/kube-setup-audit-service.sh
  gen3/bin/kube-setup-dicom-server.sh
  gen3/bin/kube-setup-requestor.sh
  kube/services/dicom-server/dicom-server-deploy.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#1931 Add data.cityofchicago.org to squid whitelist
  files/squid_whitelist/web_whitelist
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#1932 install xk6-browser and add jenkins2 deployment
  .secrets.baseline
  Docker/Jenkins-Worker/Dockerfile
  kube/services/jenkins2-worker/jenkins2-agent-service.yaml
  kube/services/jenkins2-worker/jenkins2-worker-deploy.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#1929 fix: gen3 reset - making sure all pods are turned off
  gen3/bin/reset.sh
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1934 add jenkins-perf to CI pool
  files/scripts/ci-env-pool-reset.sh
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1937 Drop connections to DB before dropping it
  gen3/bin/db.sh
  gen3/bin/reset.sh
Labels: test-portal-homepageTest

#1939 dicom-server readinessProbe and livenessProbe
  kube/services/dicom-server/dicom-server-deploy.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#1940 Fix DICOM server probes
  kube/services/dicom-server/dicom-server-deploy.yaml
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1938 removing jenkins-perf from jenkins test pool
  files/scripts/ci-env-pool-reset.sh
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1946 dicom-viewer readinessProbe and livenessProbe
  kube/services/dicom-viewer/dicom-viewer-deploy.yaml
Labels: test-apis-etlTest, skip-awshelper-build-wait, skip-gen3-helper-tests
