Repository uc-cdis/cloud-automation, pull requests merged in 2022-07, with the labels that each got.

#1987 fix command
  kube/services/jobs/metadata-aggregate-sync-job.yaml
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#1990 switch from bash to sh
  kube/services/jobs/metadata-aggregate-sync-job.yaml
Labels: test-portal-discoveryPageTest

#1978 Add Gen3Env env var
  kube/services/jobs/etl-job.yaml
Labels: test-apis-etlTest

#1991 PXP-8028 Fence DB migration: cd to where it can find Alembic files
  kube/services/fence/fence-deploy.yaml
  kube/services/jobs/fence-db-migrate-job.yaml
Labels: skip-gen3-helper-tests

#1992 Feat/kayako wrapper
  files/squid_whitelist/web_whitelist
  gen3/bin/kube-roll-all.sh
  gen3/bin/kube-setup-kayako-wrapper.sh
  kube/services/kayako-wrapper/kayako-wrapper-deploy.yaml
  kube/services/kayako-wrapper/kayako-wrapper-service.yaml
  kube/services/revproxy/gen3.nginx.conf/kayako-wrapper-service.conf
Labels: test-apis-etlTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1993 fix: secret mount
  kube/services/kayako-wrapper/kayako-wrapper-deploy.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#1995 use g3auto secrets for cedar and kayako wrapper
  doc/kube-setup-cedar-wrapper.md
  doc/kube-setup-kayako-wrapper.md
  gen3/bin/kube-setup-cedar-wrapper.sh
  gen3/bin/kube-setup-kayako-wrapper.sh
  kube/services/cedar-wrapper/cedar-wrapper-deploy.yaml
  kube/services/kayako-wrapper/kayako-wrapper-deploy.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#1994 feat(split-secondary-subnet): Split secondary subnet into 4 /18 subnets
  tf_files/aws/eks/root.tf
  tf_files/aws/eks/variables.tf
  tf_files/aws/modules/eks/cloud.tf
  tf_files/aws/modules/eks/variables.tf
Labels: skip-gen3-helper-tests

#2000 feat: add doc url
  gen3/bin/kube-setup-revproxy.sh
  kube/services/revproxy/gen3.nginx.conf/documentation-site/documentation-site.conf
  kube/services/revproxy/nginx.conf
  kube/services/revproxy/revproxy-deploy.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#2004 HP-781 Feat/heal cedar injest job
  files/scripts/healdata/heal-cedar-data-ingest.py
  kube/services/jobs/cedar-ingestion-job.yaml
Labels: skip-gen3-helper-tests
