Repository uc-cdis/cloud-automation, pull requests merged in 2022-06, with the labels that each got.

#1865 Move pip install ddtrace to Dockerfile
  Docker/python-nginx/python3.10-buster/Dockerfile
  Docker/python-nginx/python3.10-buster/dockerrun.sh
  Docker/python-nginx/python3.6-alpine3.7/Dockerfile
  Docker/python-nginx/python3.6-alpine3.7/dockerrun.sh
  Docker/python-nginx/python3.6-buster/Dockerfile
  Docker/python-nginx/python3.6-buster/dockerrun.sh
  Docker/python-nginx/python3.9-buster/Dockerfile
  Docker/python-nginx/python3.9-buster/dockerrun.sh
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#1927 Create config-local.js including iframe "keep alive" code
  .secrets.baseline
  kube/services/ohdsi-atlas/README.md
  kube/services/ohdsi-atlas/config-local.js
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#1906 Add an IAM role to every hatchery service account in cluster
  gen3/bin/kube-setup-hatchery.sh
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#1933 Feat/cedar wrapper service
  files/squid_whitelist/web_whitelist
  gen3/bin/kube-roll-all.sh
  gen3/bin/kube-setup-cedar-wrapper.sh
  kube/services/cedar-wrapper/cedar-wrapper-deploy.yaml
  kube/services/cedar-wrapper/cedar-wrapper-service.yaml
  kube/services/revproxy/gen3.nginx.conf/cedar-wrapper-service.conf
  kube/services/revproxy/nginx.conf
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#1952 use blue 3
  kube/services/portal/defaults/gitops-logo.png
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#1963 patching livenessProbe
  kube/services/portal/portal-deploy.yaml
Labels: test-apis-presignedUrlTest

#1980 Add timeout to jenkins pipeline stages
  Jenkinsfile
Labels: skip-gen3-helper-tests

#1986 Update kube-setup-cedar-wrapper.sh
  gen3/bin/kube-setup-cedar-wrapper.sh
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests
