Repository uc-cdis/cloud-automation, pull requests merged in 2022-04, with the labels that each got.

#1850 Remove unnecessary revproxy timeouts for fence and presigned-url-fence
  kube/services/presigned-url-fence/presigned-url-fence-deploy.yaml
  kube/services/revproxy/gen3.nginx.conf/fence-service-ga4gh.conf
  kube/services/revproxy/gen3.nginx.conf/fence-service.conf
Labels: skip-gen3-helper-tests

#1839 Bringing DICOM Viewer to cloud automation
  .github/workflows/image_build_push.yaml
  .secrets.baseline
  gen3/bin/kube-roll-all.sh
  gen3/bin/kube-setup-dicom-server.sh
  gen3/bin/kube-setup-dicom-viewer.sh
  kube/services/dicom-server/dicom-server-deploy.yaml
  kube/services/dicom-server/dicom-server-service.yaml
  kube/services/dicom-viewer/dicom-viewer-deploy.yaml
  kube/services/dicom-viewer/dicom-viewer-service.yaml
  kube/services/revproxy/gen3.nginx.conf/dicom-server-service.conf
  kube/services/revproxy/gen3.nginx.conf/dicom-viewer-service.conf
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-apis-centralizedAuth, skip-quay-build

#1899 Add DD_AGENT_HOST env var
  kube/services/jenkins-worker/jenkins-worker-deployment.yaml
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, skip-quay-build

#1898 Update datadog values.yaml
  kube/services/datadog/values.yaml
Labels: test-apis-dataUploadTest, skip-awshelper-build-wait, skip-gen3-helper-tests, test-apis-centralizedAuth, skip-quay-build

#1905 dicom-server client_max_body_size 0
  kube/services/revproxy/gen3.nginx.conf/dicom-server-service.conf
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests, skip-quay-build

#1907 roll-all: move DICOM services to the right spot
  gen3/bin/kube-roll-all.sh
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, skip-quay-build

#1904 fix spacing issues in argo-wrapper deploy
  kube/services/argo-wrapper/argo-wrapper-deploy.yaml
Labels: test-apis-etlTest, test-apis-dataUploadTest, skip-awshelper-build-wait, skip-gen3-helper-tests, test-guppy-guppyTest, test-apis-centralizedAuth, skip-quay-build

#1908 fix add missing configs to argo archieve db
  kube/services/argo/values.yaml
Labels: test-apis-etlTest, skip-awshelper-build-wait, skip-gen3-helper-tests, skip-quay-build

#1909 install all tools on jenkins2
  Docker/Jenkins2/Dockerfile
  Docker/Jenkins2/install-python3.8.sh
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1915 (PXP-9849): Fix mutate-guppy-config-for-pfb-export-test.sh so that index and type match
  doc/gitops.md
  gen3/bin/gitops.sh
  gen3/bin/mutate-etl-mapping-config.sh
  gen3/bin/mutate-guppy-config-for-pfb-export-test.sh
Labels: test-apis-etlTest, skip-awshelper-build-wait, skip-gen3-helper-tests, skip-quay-build

#1917 fix jenkins and jenkins2 deployments
  gen3/bin/kube-setup-jenkins.sh
  kube/services/jenkins-ci-worker/jenkins-ci-worker-deploy.yaml
  kube/services/jenkins-ci-worker/jenkins-ci-worker-pvc.yaml
  kube/services/jenkins-worker/jenkins-worker-deploy.yaml
  kube/services/jenkins2/jenkins2-deploy.yaml
Labels: skip-awshelper-build-wait
