Repository uc-cdis/cloud-automation, pull requests merged in 2022-02, with the labels that each got.

#1486 fix(cycle-script): Added a cordon step before draining nodes so new p…
  gen3/bin/workers-cycle.sh
Labels: test-apis-dataUploadTest

#1693 Add data-commons.org to whitelist
  files/squid_whitelist/web_wildcard_whitelist
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1832 feat add argo-wrapper deployment
  gen3/bin/kube-setup-argo-wrapper.sh
  kube/services/argo-wrapper/argo-wrapper-deploy.yaml
  kube/services/argo-wrapper/argo-wrapper-service.yaml
  kube/services/revproxy/gen3.nginx.conf/argo-wrapper-service.conf
Labels: test-sheepdogAndPeregrine-submitAndQueryNodesTest

#1517 chore(ci-infra): Document network policies required for Jenkins2 and Selenium-hub in qaplanetv2
  Docker/Jenkins2/README.md
  Docker/Jenkins2/k8sjenkins-agent-master-policy.yaml
  Docker/Jenkins2/k8sjenkins-agent-policy.yaml
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1841 delete only folders more than 5 days old
  files/scripts/jenkins-cronjob.sh
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1842 PXP-9499 WTS init container: add SECRET_CONFIG
  apis_configs/indexd_settings.py
  gen3/bin/kube-setup-wts.sh
  kube/services/wts/wts-deploy.yaml
Labels: skip-gen3-helper-tests

#1843 Add fence keys for cdis-test sftp access
  files/authorized_keys/squid_authorized_keys_user
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#1847 (PXP-9536): fix `gen3 logs snapshot` when there are "Pending" pods
  gen3/lib/logs/snapshot.sh
Labels: skip-gen3-helper-tests

#1848 covid19-notebok-etl job: do not overwrite the startup commands
  kube/services/jobs/covid19-notebook-etl-job.yaml
Labels: skip-gen3-helper-tests
