Repository uc-cdis/cloud-automation, pull requests merged in 2022-03, with the labels that each got.

#1857 influxdb - fix max_series_per_database limitation
  kube/services/influxdb/influxdb-deployment.yaml
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#1862 Default user.yaml passes validation
  apis_configs/user.yaml
  gen3/bin/kube-setup-fenceshib.sh
  gen3/bin/kube-setup-peregrine.sh
  gen3/bin/kube-setup-pidgin.sh
  gen3/bin/kube-setup-sftp.sh
  gen3/bin/kube-setup-sheepdog.sh
  gen3/bin/kube-setup-spark.sh
  gen3/bin/kube-setup-tty.sh
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests, test-sheepdogAndPeregrine-submitAndQueryNodesTest, test-guppy-guppyTest, test-apis-requestorTest

#1870 chore: Whiteslist apt.kubernetes.io
  files/squid_whitelist/web_whitelist
Labels: test-guppy-guppyTest, test-pidgin-getCoremetadataTest
