Repository uc-cdis/cloud-automation, pull requests merged in 2022-08, with the labels that each got.

#2010 add thor to psql-fips-fix.sh
  files/scripts/psql-fips-fix.sh
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#2011 PXP-GPE-480
  kube/services/jenkins/rolebinding-devops.yaml
Labels: test-apis-nonDbgapUsersyncTest

#2013 Update web_whitelist
  files/squid_whitelist/web_whitelist
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#2002 add kube-setup-thor
  gen3/bin/kube-setup-thor.sh
  kube/services/revproxy/gen3.nginx.conf/thor-service.conf
  kube/services/thor/thor-deploy.yaml
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#2025 pull branch in initContainer
  kube/services/thor/thor-deploy.yaml
Labels: test-portal-homepageTest

#2028 Update thor-deploy.yaml
  kube/services/thor/thor-deploy.yaml
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#2031 add env var to thor deploy
  kube/services/thor/thor-deploy.yaml
Labels: test-portal-homepageTest, skip-gen3-helper-tests
