Repository uc-cdis/cloud-automation, pull requests merged in 2023-05, with the labels that each got.

#2229 (PPS-212): add header to portal to prevent clickjacking
  kube/services/revproxy/gen3.nginx.conf/portal-as-root/portal-service.conf
Labels: test-apis-etlTest, test-portal-dataUploadTest, skip-gen3-helper-tests, test-portal-coremetadatapageTest, test-coremetadata-getCoremetadataTest

#2242 Switch gen3Env to hostname instead of environment
  Jenkinsfile
  kube/services/jobs/etl-cronjob.yaml
  kube/services/jobs/fence-db-migrate-job.yaml
  kube/services/jobs/fence-visa-update-cronjob.yaml
  kube/services/jobs/fence-visa-update-job.yaml
  kube/services/jobs/s3sync-cronjob.yaml
  kube/services/jobs/usersync-job.yaml
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#2211 making cronjob fence-visa-update optional
  gen3/bin/kube-setup-fence.sh
Labels: test-apis-etlTest, test-portal-dataUploadTest, skip-gen3-helper-tests, test-portal-coremetadatapageTest, test-coremetadata-getCoremetadataTest

#2247 Add jenkins-new-1 to CI pool
  files/scripts/ci-env-pool-reset.sh
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#2248 Add containerd support for jenkins worker
  kube/services/jenkins-worker/jenkins-worker-deploy.yaml
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#2251 Set AWS default region in Thor deployment
  kube/services/thor/thor-deploy.yaml
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#2252 update jenkins dockers to python 3.9
  Docker/jenkins/Jenkins-Worker/Dockerfile
  Docker/jenkins/Jenkins-Worker/install-python3.8.sh
  Docker/jenkins/Jenkins-Worker/install-python3.9.sh
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#2261 Update logo.svg
  apis_configs/logo.svg
Labels: skip-gen3-helper-tests

#2232 HP-1117 Feat/cedar ingest update
  files/scripts/healdata/heal-cedar-data-ingest.py
Labels: skip-gen3-helper-tests

#2254 (HP-1106): read license from kubernetes secret
  kube/services/jobs/distribute-licenses-job.yaml
Labels: test-apis-etlTest, test-portal-dataUploadTest, skip-gen3-helper-tests
