Repository uc-cdis/cloud-automation, pull requests merged in 2023-08, with the labels that each got.

#2302 Update kube-roll-all.sh
  gen3/bin/kube-roll-all.sh
  gen3/bin/kube-setup-cohort-middleware.sh
Labels: skip-awshelper-build-wait, skip-gen3-helper-tests

#2304 install go binary in jenkins CI worker
  .secrets.baseline
  Docker/jenkins/Jenkins-CI-Worker/Dockerfile
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#2323 Revert kubelet config change
  kube/services/argo-events/workflows/configmap.yaml
Labels: skip-gen3-helper-tests

#2325 Add k6 to jenkins-worker
  Docker/jenkins/Jenkins-Worker/Dockerfile
Labels: test-portal-homepageTest, skip-gen3-helper-tests
