Repository uc-cdis/cloud-automation, pull requests merged in 2023-03, with the labels that each got.

#2170 Remove limits in portal kube config
  kube/services/portal/portal-deploy.yaml
  kube/services/portal/portal-root-deploy.yaml
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#2161 Fix/cedar typo
  files/scripts/healdata/heal-cedar-data-ingest.py
Labels: test-apis-etlTest, skip-gen3-helper-tests

#2176 Revert "Use jenkins-niaid for service PRs"
  files/scripts/ci-env-pool-reset.sh
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#2182 chore/add slack status messages to mds-agg-sync
  kube/services/jobs/metadata-aggregate-sync-job.yaml
Labels: test-apis-etlTest, skip-gen3-helper-tests

#2081 Reduce pod sizes based on metrics
  gen3/lib/testData/default/expectedFenceResult.yaml
  gen3/lib/testData/default/expectedSheepdogResult.yaml
  gen3/lib/testData/test1.manifest.g3k/expectedFenceResult.yaml
  gen3/lib/testData/test1.manifest.g3k/expectedSheepdogResult.yaml
  kube/services/access-backend/access-backend-deploy.yaml
  kube/services/acronymbot/acronymbot-deploy.yaml
  kube/services/ambassador-gen3/ambassador-gen3-deploy.yaml
  kube/services/ambassador/ambassador-deploy.yaml
  kube/services/arborist/arborist-deploy-2.yaml
  kube/services/audit-service/audit-service-deploy.yaml
  kube/services/auspice/auspice-deploy.yaml
  kube/services/autoscaler/cluster-autoscaler-autodiscover.yaml
  kube/services/aws-es-proxy/aws-es-proxy-deploy.yaml
  kube/services/cedar-wrapper/cedar-wrapper-deploy.yaml
  kube/services/cohort-middleware/cohort-middleware-deploy.yaml
  kube/services/dashboard/dashboard-deploy.yaml
  kube/services/fence/fence-deploy.yaml
  kube/services/fenceshib/fenceshib-deploy.yaml
  kube/services/frontend-framework/frontend-framework-deploy.yaml
  kube/services/guppy/guppy-deploy.yaml
  kube/services/indexd/indexd-deploy.yaml
  kube/services/manifestservice/manifestservice-deploy.yaml
  kube/services/metadata/metadata-deploy.yaml
  kube/services/ohdsi-atlas/ohdsi-atlas-deploy.yaml
  kube/services/ohdsi-webapi/ohdsi-webapi-deploy.yaml
  kube/services/peregrine/peregrine-deploy.yaml
  kube/services/pidgin/pidgin-deploy.yaml
  kube/services/presigned-url-fence/presigned-url-fence-deploy.yaml
  kube/services/requestor/requestor-deploy.yaml
  kube/services/revproxy/revproxy-deploy.yaml
  kube/services/sheepdog/sheepdog-deploy.yaml
  kube/services/sower/sower-deploy.yaml
  kube/services/ssjdispatcher/ssjdispatcher-deploy.yaml
  kube/services/wts/wts-deploy.yaml
Labels: skip-gen3-helper-tests

#2186 cedar ingestion revproxy
  files/scripts/healdata/heal-cedar-data-ingest.py
Labels: skip-gen3-helper-tests
