Repository uc-cdis/cloud-automation, pull requests merged in 2023-07, with the labels that each got.

#2294 Add new new envs to CI pool
  files/scripts/ci-env-pool-reset.sh
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#2289 chore/read gen3 license from g3auto secret
  kube/services/jobs/distribute-licenses-job.yaml
Labels: test-apis-etlTest, skip-gen3-helper-tests

#2297 Update jenkins to latest versions
  .github/workflows/image_build_push_jenkins.yaml
  .secrets.baseline
  Docker/jenkins/Jenkins-CI-Worker/Dockerfile
  Docker/jenkins/Jenkins-Worker/Dockerfile
  Docker/jenkins/Jenkins/Dockerfile
  Docker/jenkins/Jenkins2/Dockerfile
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#2299 Add missing jenkins dependencies
  .secrets.baseline
  Docker/jenkins/Jenkins-CI-Worker/Dockerfile
  Docker/jenkins/Jenkins-Worker/Dockerfile
  Docker/jenkins/Jenkins/Dockerfile
  Docker/jenkins/Jenkins2/Dockerfile
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#2268 HP-1083 Feat/cedar mds update
  files/scripts/healdata/heal-cedar-data-ingest.py
Labels: skip-gen3-helper-tests
