Repository uc-cdis/cloud-automation, pull requests merged in 2024-02, with the labels that each got.

#2455 Update jenkins version
  Docker/jenkins/Jenkins/Dockerfile
  Docker/jenkins/Jenkins2/Dockerfile
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#2454 HP-1333 update script
  files/scripts/healdata/heal-cedar-data-ingest.py
Labels: test-apis-etlTest, test-apis-dataUploadTest, test-portal-dataUploadTest, skip-gen3-helper-tests, test-sheepdogAndPeregrine-submitFileTest, test-sheepdogAndPeregrine-submitAndQueryNodesTest, test-portal-indexingPageTest, test-portal-loginPageTest, test-apis-metadataIngestionTest, test-portal-exportToWorkspaceTest

#2478 gen3 logs snapshot: also get initContainers logs
  gen3/lib/logs/snapshot.sh
Labels: skip-gen3-helper-tests

#2484 Prevent eviction of ETL job pod while running
  kube/services/jobs/etl-job.yaml
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#2472 updating the cedar data ingest
  files/scripts/healdata/heal-cedar-data-ingest.py
Labels: skip-gen3-helper-tests

#2489 Add jenkins-dcp to the env pool reset script
  files/scripts/ci-env-pool-reset.sh
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#2441 (HP-572) create dynamodb table for gen3-license workspace
  gen3/bin/kube-setup-hatchery.sh
Labels: test-apis-etlTest, skip-gen3-helper-tests
