Repository uc-cdis/cloud-automation, pull requests merged in 2024-05, with the labels that each got.

#2533 MIDRC-639 DICOM viewer v3: fix prefix in config and port
  gen3/bin/kube-setup-dicom.sh
  kube/services/dicom-viewer/dicom-viewer-service.yaml
  kube/services/ohif-viewer/ohif-viewer-deploy.yaml
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#2550 pass AGG_MDS_DEFAULT_DATA_DICT_FIELD to mds
  kube/services/jobs/metadata-aggregate-sync-job.yaml
  kube/services/metadata/metadata-deploy.yaml
Labels: test-apis-metadataIngestionTest

#2551 Update heal-cedar-data-ingest.py
  files/scripts/healdata/heal-cedar-data-ingest.py
Labels: test-apis-metadataIngestionTest

#2040 fix(migrate_acl): allow loading and preference of authz mapping from …
  kube/services/jobs/indexd-authz-job.yaml
Labels: test-apis-exportToWorkspaceTest, test-portal-exportToWorkspaceTest

#2544 Feat: new settings for the "global cohorts" feature
  gen3/bin/kube-setup-cohort-middleware.sh
  kube/services/ohdsi-atlas/ohdsi-atlas-config-local.yaml
Labels: test-apis-clientCredGrantTest
