Repository uc-cdis/cloud-automation, pull requests merged in 2024-03, with the labels that each got.

#2495 Raising requests for Jenkins pods
  .secrets.baseline
  Jenkinsfile
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#2494 fix cedar ingestion problems
  .secrets.baseline
  files/scripts/healdata/heal-cedar-data-ingest.py
Labels: skip-gen3-helper-tests

#2480 MIDRC-602 Add ecr-access job
  .pre-commit-config.yaml
  .secrets.baseline
  files/scripts/ecr-access-job-requirements.txt
  files/scripts/ecr-access-job.md
  files/scripts/ecr-access-job.py
  gen3/bin/kube-setup-ecr-access-cronjob.sh
  kube/services/jobs/ecr-access-job.yaml
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests

#2497 Add new middleware url
  kube/services/argo-wrapper/config.ini
Labels: test-portal-homepageTest, skip-gen3-helper-tests

#2498 HP-1310 feat: updated related studies logic
  files/scripts/healdata/heal-cedar-data-ingest.py
Labels: test-apis-etlTest, skip-gen3-helper-tests

#2500 Add alt text to maintenance page images
  files/dashboard/maintenance-page/index.html
Labels: skip-gen3-helper-tests

#2515 MIDRC-672 Fix ECR access job role name conflict
  gen3/bin/iam-serviceaccount.sh
  gen3/bin/kube-setup-ecr-access-cronjob.sh
Labels: test-portal-homepageTest, skip-awshelper-build-wait, skip-gen3-helper-tests
