Repository uc-cdis/cloud-automation, pull requests merged in 2025-04, with the labels that each got.

#2761 Update web_whitelist
  files/squid_whitelist/web_whitelist
Labels: TestAggregateMDS, TestDicomViewer

#2751 Data Replicate Update
  .secrets.baseline
  gen3/bin/kube-setup-data-replicate.sh
  kube/services/jobs/remove-objects-from-clouds-job.yaml
Labels: TestDataUpload

#2765 Update qabot-deploy.yaml
  kube/services/qabot/qabot-deploy.yaml
Labels: TestHomePage

#2775 Update kube-setup-access-backend.sh
  gen3/bin/kube-setup-access-backend.sh
Labels: doc-only
