Repository uc-cdis/cloud-automation, pull requests merged in 2025-01, with the labels that each got.

#2657 Fix/single table job fixes
  kube/services/jobs/indexd-single-table-migration-job.yaml
  kube/services/jobs/indexd-single-table-migration-priority-class.yaml
Labels: TestAuditService

#2693 Remove unused lines in `spark-deploy.yaml`
  .pre-commit-config.yaml
  kube/services/spark/spark-deploy.yaml
Labels: TestAggregateMDS, TestAuditService, TestDrsEndpoints

#2682 Add changes to ensure azlinux and mcrypt images are working fine
  .secrets.baseline
  gen3/lib/testData/default/expectedFenceResult.yaml
  gen3/lib/testData/test1.manifest.g3k/expectedFenceResult.yaml
  kube/services/argo/workflows/fence-usersync-wf.yaml
  kube/services/datasim/datasim-deploy.yaml
  kube/services/fence/fence-canary-deploy.yaml
  kube/services/fence/fence-deploy.yaml
  kube/services/fenceshib/fenceshib-canary-deploy.yaml
  kube/services/fenceshib/fenceshib-deploy.yaml
  kube/services/google-sa-validation/google-sa-validation-deploy.yaml
  kube/services/jobs/client-modify-job.yaml
  kube/services/jobs/fence-cleanup-expired-ga4gh-info-cronjob.yaml
  kube/services/jobs/fence-cleanup-expired-ga4gh-info-job.yaml
  kube/services/jobs/fence-db-migrate-job.yaml
  kube/services/jobs/fence-delete-expired-clients-job.yaml
  kube/services/jobs/fence-visa-update-cronjob.yaml
  kube/services/jobs/fence-visa-update-job.yaml
  kube/services/jobs/fencedb-create-job.yaml
  kube/services/jobs/gen3qa-check-bucket-access-job.yaml
  kube/services/jobs/gentestdata-job.yaml
  kube/services/jobs/google-create-bucket-job.yaml
  kube/services/jobs/google-delete-expired-access-cronjob.yaml
  kube/services/jobs/google-delete-expired-access-job.yaml
  kube/services/jobs/google-delete-expired-service-account-cronjob.yaml
  kube/services/jobs/google-delete-expired-service-account-job.yaml
  kube/services/jobs/google-init-proxy-groups-cronjob.yaml
  kube/services/jobs/google-init-proxy-groups-job.yaml
  kube/services/jobs/google-manage-account-access-cronjob.yaml
  kube/services/jobs/google-manage-account-access-job.yaml
  kube/services/jobs/google-manage-keys-cronjob.yaml
  kube/services/jobs/google-manage-keys-job.yaml
  kube/services/jobs/google-verify-bucket-access-group-cronjob.yaml
  kube/services/jobs/google-verify-bucket-access-group-job.yaml
  kube/services/jobs/usersync-job.yaml
  kube/services/jobs/useryaml-job.yaml
  kube/services/presigned-url-fence/presigned-url-fence-deploy.yaml
Labels: TestGoogleDataAccess, TestDbgap

#2707 Paulineribeyre patch 1
  gen3/bin/kube-roll-all.sh
Labels: TestAuditService

#2711 Update web_wildcard_whitelist
  packer/configs/web_wildcard_whitelist
Labels: TestDataUpload, TestDicomViewer

#2708 Add `poetry run` for fence-create with backwards compatibility
  gen3/bin/api.sh
  gen3/bin/dcf.sh
  gen3/bin/kube-setup-apache-guacamole.sh
  gen3/bin/kube-setup-cedar-wrapper.sh
  gen3/bin/kube-setup-metadata-delete-expired-objects-cronjob.sh
  gen3/bin/kube-setup-ohdsi.sh
  gen3/bin/kube-setup-pelicanjob.sh
  gen3/bin/kube-setup-superset.sh
  gen3/bin/kube-setup-wts.sh
  gen3/lib/testData/default/expectedFenceResult.yaml
  gen3/lib/testData/test1.manifest.g3k/expectedFenceResult.yaml
  kube/services/argo/workflows/fence-usersync-wf.yaml
  kube/services/datasim/datasim-deploy.yaml
  kube/services/fence/fence-deploy.yaml
  kube/services/jobs/client-modify-job.yaml
  kube/services/jobs/fence-cleanup-expired-ga4gh-info-cronjob.yaml
  kube/services/jobs/fence-cleanup-expired-ga4gh-info-job.yaml
  kube/services/jobs/fence-db-migrate-job.yaml
  kube/services/jobs/fence-delete-expired-clients-job.yaml
  kube/services/jobs/fence-visa-update-cronjob.yaml
  kube/services/jobs/fence-visa-update-job.yaml
  kube/services/jobs/gen3qa-check-bucket-access-job.yaml
  kube/services/jobs/gentestdata-job.yaml
  kube/services/jobs/google-create-bucket-job.yaml
  kube/services/jobs/google-delete-expired-access-cronjob.yaml
  kube/services/jobs/google-delete-expired-access-job.yaml
  kube/services/jobs/google-delete-expired-service-account-cronjob.yaml
  kube/services/jobs/google-delete-expired-service-account-job.yaml
  kube/services/jobs/google-init-proxy-groups-cronjob.yaml
  kube/services/jobs/google-init-proxy-groups-job.yaml
  kube/services/jobs/google-manage-account-access-cronjob.yaml
  kube/services/jobs/google-manage-account-access-job.yaml
  kube/services/jobs/google-manage-keys-cronjob.yaml
  kube/services/jobs/google-manage-keys-job.yaml
  kube/services/jobs/google-verify-bucket-access-group-cronjob.yaml
  kube/services/jobs/google-verify-bucket-access-group-job.yaml
  kube/services/jobs/usersync-job.yaml
  kube/services/jobs/useryaml-job.yaml
Labels: TestAuditService

#2716 Revert/fallback_to_poetry_run
  .secrets.baseline
  gen3/bin/api.sh
  gen3/bin/dcf.sh
  gen3/bin/kube-setup-apache-guacamole.sh
  gen3/bin/kube-setup-cedar-wrapper.sh
  gen3/bin/kube-setup-metadata-delete-expired-objects-cronjob.sh
  gen3/bin/kube-setup-ohdsi.sh
  gen3/bin/kube-setup-pelicanjob.sh
  gen3/bin/kube-setup-superset.sh
  gen3/bin/kube-setup-wts.sh
  gen3/lib/testData/default/expectedFenceResult.yaml
  gen3/lib/testData/test1.manifest.g3k/expectedFenceResult.yaml
  kube/services/argo/workflows/fence-usersync-wf.yaml
  kube/services/datasim/datasim-deploy.yaml
  kube/services/fence/fence-canary-deploy.yaml
  kube/services/fence/fence-deploy.yaml
  kube/services/fenceshib/fenceshib-canary-deploy.yaml
  kube/services/fenceshib/fenceshib-deploy.yaml
  kube/services/google-sa-validation/google-sa-validation-deploy.yaml
  kube/services/jobs/client-modify-job.yaml
  kube/services/jobs/fence-cleanup-expired-ga4gh-info-cronjob.yaml
  kube/services/jobs/fence-cleanup-expired-ga4gh-info-job.yaml
  kube/services/jobs/fence-db-migrate-job.yaml
  kube/services/jobs/fence-delete-expired-clients-job.yaml
  kube/services/jobs/fence-visa-update-cronjob.yaml
  kube/services/jobs/fence-visa-update-job.yaml
  kube/services/jobs/fencedb-create-job.yaml
  kube/services/jobs/gen3qa-check-bucket-access-job.yaml
  kube/services/jobs/gentestdata-job.yaml
  kube/services/jobs/google-create-bucket-job.yaml
  kube/services/jobs/google-delete-expired-access-cronjob.yaml
  kube/services/jobs/google-delete-expired-access-job.yaml
  kube/services/jobs/google-delete-expired-service-account-cronjob.yaml
  kube/services/jobs/google-delete-expired-service-account-job.yaml
  kube/services/jobs/google-init-proxy-groups-cronjob.yaml
  kube/services/jobs/google-init-proxy-groups-job.yaml
  kube/services/jobs/google-manage-account-access-cronjob.yaml
  kube/services/jobs/google-manage-account-access-job.yaml
  kube/services/jobs/google-manage-keys-cronjob.yaml
  kube/services/jobs/google-manage-keys-job.yaml
  kube/services/jobs/google-verify-bucket-access-group-cronjob.yaml
  kube/services/jobs/google-verify-bucket-access-group-job.yaml
  kube/services/jobs/usersync-job.yaml
  kube/services/jobs/useryaml-job.yaml
  kube/services/presigned-url-fence/presigned-url-fence-deploy.yaml
Labels: TestHomePage, TestETL
