Repository uc-cdis/cloud-automation, pull requests merged in 2025-03, with the labels that each got.

#2695 (HP-1825): Script for automated launch test of workspaces
  files/scripts/workspaces_launch_test.py
  kube/services/jobs/workspace-launch-test-cronjob.yaml
  kube/services/jobs/workspace-launch-test-job.yaml
Labels: TestHomePage

#2735 Use CLOUD_AUTO_BRANCH for integration tests
  .github/workflows/integration_tests.yaml
Labels: TestHomePage

#2742 MIDRC-945 Add `s3:DeleteBucket` in kube-setup-gen3-workflow
  gen3/bin/kube-setup-gen3-workflow.sh
Labels: TestDbgap, TestGraphSubmitAndQuery

#2752 Feat: slightly increase webapi timeout to not conflict with gen3 one
  kube/services/ohdsi-webapi/ohdsi-webapi-config.yaml
Labels: TestAuditService, TestDataUpload, TestDiscoveryPage
