Repository uc-cdis/cloud-automation, pull requests merged in 2025-02, with the labels that each got.

#2718 Usersync fixes for ccrypt
  .secrets.baseline
  kube/services/jobs/usersync-job.yaml
Labels: TestAggregateMDS

#2721 Update web_whitelist
  files/squid_whitelist/web_whitelist
Labels: TestDataUpload, TestDicomViewer

#2723 Gen3Workflow and Funnel deployment
  .secrets.baseline
  gen3/bin/db.sh
  gen3/bin/kube-roll-all.sh
  gen3/bin/kube-setup-audit-service.sh
  gen3/bin/kube-setup-gen3-workflow.sh
  gen3/bin/kube-setup-requestor.sh
  gen3/bin/s3.sh
  kube/services/gen3-workflow/gen3-workflow-deploy.yaml
  kube/services/gen3-workflow/gen3-workflow-service.yaml
  kube/services/revproxy/gen3.nginx.conf/gen3-workflow-service.conf
Labels: TestAuditService, TestWorkspacePage

#2726 Update web_whitelist
  files/squid_whitelist/web_whitelist
Labels: TestAggregateMDS, TestRasAuthN

#2730 Update sample.tfvars
  tf_files/aws/commons/sample.tfvars
Labels: TestAuditService, TestDbgap, TestDataUpload, TestDicomViewer, TestWorkspacePage, TestDiscoveryPage

#2686 Fix Google Bucket Job
  .secrets.baseline
  Docker/awshelper/Dockerfile
  kube/services/jobs/aws-bucket-replicate-job.yaml
  kube/services/jobs/google-bucket-replicate-job.yaml
  kube/services/jobs/replicate-validation-job.yaml
Labels: TestAuditService

#2738 Add health probes to access-backend
  .secrets.baseline
  kube/services/access-backend/access-backend-deploy.yaml
Labels: TestAuditService, TestDbgap
